---
title: ""
output:
  html_document:
    highlight: "tango"
editor_options: 
  chunk_output_type: inline
---

### National and State Level Data

The COVID-19 deaths, cases, and tests are taken from the 
<a href="https://covidtracking.com/data/download" target= "_blank">
Covid Tracking Project</a>.  

Population numbers are taken from the 
<a href="https://www.census.gov/data/datasets/time-series/demo/popest/2010s-state-total.html#par_textimage_1873399417" target = "_blank">
US Census State Population Totals</a>. 
Note that the projected population for 2019 were used.  

### County Level Data

COVID-19 cases at the county level are taken from
<a href="https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series" target= "_blank">
Johns Hopkins</a>.  

Population numbers are taken from the 
<a href="https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html" target = "_blank">
US Census County Population Totals</a>. 
Note that the projected population for 2019 were used.  

### Plot Dates 

Many of the plots have been restricted to show data on March 15, 2020 and after.  This is when case numbers started to rise and preventative measures started to increase dramatically.  

### Data Limitations 

A large limitation for this data is that reported new cases (and thus the growth factor) may not consistently and accurately represent the true number of new cases each day.  As mentioned before, this could be due to test availability, reporting protocols, and a number of other variables.  It is important to note that this information is a helpful tool in trying to understand the pandemic, but it may not reflect the entire story.  
 
