---
title: ""
output:
  html_document:
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---

```{r state-outside-script, results="hide", warning=FALSE, message=FALSE, include = FALSE}
# source("script/variable/setup.R")
# source("script/dataframe/covid19.R") #run script for covid19 df
# source("script/variable/parameters.R") #global parameters
```

```{r state-facet-data}
facet_data <- covid19 %>%
  filter(geo %in% c(state.abb, "DC")) %>% 
  filter(date >= x_min) #x_min from parameters.R file 
```


```{r state-MA7PC, fig.height= 5.75}

title <- paste("7-Day Moving Average of New Cases per 100,000 ")
subtitle <- paste(min(facet_data$date), "to", max(facet_data$date)) 

max_val <- RoundTo(max(facet_data$case_MA7_PC_100k), multiple = 5)

  
ggplot(facet_data, aes(date, case_MA7_PC_100k)) + 
    geom_area(fill = blue_comp, alpha = 0.2) + 
    geom_line(color = blue_comp) +
    facet_geo(~geo, grid = "us_state_grid2" , labeller = adjust_labels, scales = "fixed") +
    scale_x_date(      name = NULL, expand = c(0, 0), breaks = NULL) + 
    scale_y_continuous(
        name = NULL
      , expand = c(0, 0)
      , breaks = c(0, max_val)
      , limits = c(0, max_val)
                       ) +
    theme_minimal() +
    labs(
      title = title
      , subtitle = subtitle
    ) +
    theme_minimal() +
    theme(
        strip.text = element_text(margin = margin(3, 3, 3, 3), face = "bold")
      , plot.title = element_text(face = "bold", hjust = 0.5)
      , plot.subtitle = element_text(hjust = 0.5, size = 12)
      , axis.text.y  = element_text(size = 7)
      , panel.grid = element_blank()
      , panel.background = element_rect(color = "grey80")
      , legend.position = "top"
    ) 
```


&nbsp; 

```{r state-MA7PC-2weeks, fig.height= 5.75}

last14days_facet_data <- facet_data %>%
  filter(date > max(date) -14)  %>%
  select(date, geo, case_new_PC_100k, case_MA7_PC_100k) 

last14days_facet_data <- last14days_facet_data %>%
  filter(date == min(date) | date == max(date)) %>% 
  select(date, geo, case_MA7_PC_100k) %>%
  pivot_wider(., names_from = date, values_from = case_MA7_PC_100k) %>%
  select(geo, min_date = 2, max_date = 3) %>%
  mutate(trend = ifelse(min_date <= max_date, "Increasing", "Decreasing")) %>%
  select(geo, trend) %>%
  left_join(last14days_facet_data, ., by = "geo")


title <- paste("New Cases per 100,000 last 2 Weeks")
subtitle <- paste(min(last14days_facet_data$date), "to", max(last14days_facet_data$date)) 

max_val <- RoundTo(max(last14days_facet_data$case_new_PC_100k), multiple = 5)

mye_green <- brewer.pal(n=7, "RdYlGn")[7]
mye_red   <- brewer.pal(n=7, "RdYlGn")[1]

colors_indec <- c(
    brewer.pal(n=7, "RdYlGn")[7]
    , brewer.pal(n=7, "RdYlGn")[1]
  )

names(colors_indec) <-  c("Decreasing", "Increasing")
  
ggplot(last14days_facet_data, aes(date, case_MA7_PC_100k)) + 
    geom_col(aes(y = case_new_PC_100k), alpha=0.3) +
    #geom_area(alpha = 0.2, aes(fill = trend)) + 
    geom_line(aes(color = trend), alpha = 0.6) + 
    facet_geo(~geo, grid = "us_state_grid2" , labeller = adjust_labels, scales = "fixed") +
    scale_color_manual(name = "Trend of 7-Day Moving Average", values = colors_indec, drop = FALSE) + 
    scale_x_date(      name = NULL, expand = c(0, 0), breaks = NULL) + 
    scale_y_continuous(
        name = NULL
      , expand = c(0, 0)
      , breaks = c(0, max_val)
      , limits = c(0, max_val)
                       ) +
    theme_minimal() +
    labs(
      title = title
      , subtitle = subtitle
    ) +
    theme_minimal() +
    theme(
        strip.text = element_text(margin = margin(3, 3, 3, 3), face = "bold")
      , plot.title = element_text(face = "bold", hjust = 0.5)
      , plot.subtitle = element_text(hjust = 0.5, size = 12)
      , axis.text.y  = element_text(size = 7)
      , panel.grid = element_blank()
      , panel.background = element_rect(color = "grey80")
      , legend.position = "top"
    ) 
```

&nbsp; 

```{r gf-facet-data}
gf_facet_val <- covid19 %>%
  filter(geo %in% c(state.abb, "DC")) %>% 
  filter(date > max(date) - 14)  #x_min from parameters.R file 

gf_facet_max <- gf_facet_val %>%
  group_by(geo) %>%
  summarize(max_gf_from_one = max(gf_MA7)-1)

gf_facet <- left_join(gf_facet_val, gf_facet_max)
```


```{r state-MA7gf, fig.height= 5.75}

min_gf_val <- min(RoundTo(min(gf_facet$gf_MA7) - 1, multiple = 0.05), -0.1)
  
ggplot(gf_facet, aes(date, y = gf_MA7 - 1)) + 
    geom_area(aes(y = max_gf_from_one), fill = gf_red, alpha = 0.15) +
    geom_area(fill = blue_comp, alpha = 0.5) + 
    facet_geo(~geo, grid = "us_state_grid2" , scales = "free") +
    scale_x_date(      name = NULL, expand = c(0, 0), breaks = NULL) + 
     scale_y_continuous(
         name = NULL
       , expand = c(0, 0)
                        ) +
    labs(
      title = "Individual State 7-Day Moving Average Growth Factor Last Two Weeks"
      , subtitle =  "Growth Factor Difference from One"
      , caption = paste0(
        "Dates range from ", min(gf_facet$date), " to ", max(gf_facet$date)
        , "\n"
        , "A growth factor less than one (difference less than zero) means new cases are decreasing"
      )
      ) + 
    theme_minimal() +
    theme(
        strip.text = element_text(margin = margin(3, 3, 3, 3), face = "bold")
      , plot.title = element_text(hjust = 0.5, size = title_size)
      , plot.subtitle = element_text(hjust = 0.5, size = subtitle_size)
      , axis.text.y  = element_text(size = 7)
      , panel.grid = element_blank()
      , panel.background = element_rect(color = "grey80")
      , legend.position = "top"
    ) 
```

```{r, out.width = "100%", eval = FALSE }
### Take a Closer Look! 

# Build your own plot for a given state and time period by using a shiny app.  The app can be access through this  link, <a href="https://mareichler.shinyapps.io/diy-covid19-plots/" target = "_blank">mareichler.shinyapps.io/diy-covid19-plots/</a>, and is also embedded below:  
# knitr::include_app("https://mareichler.shinyapps.io/diy-covid19-plots/", height = "500px")
```






