---
title: ""
output:
  html_document:
    highlight: "tango"
editor_options: 
  chunk_output_type: console
---

```{r total-outside-script, results="hide", warning=FALSE, message=FALSE, include = FALSE}
# source("script/variable/setup.R")
# source("script/dataframe/covid19.R") #run script for covid19 df
# source("script/dataframe/covid19_county.R") #run script for covid19 df
# source("script/variable/parameters.R") #global parameters
```


```{r state-total-MA7-PC, fig.height=5, fig.width = 8}

#HEX MAP SET UP

#INFO HERE: https://www.r-graph-gallery.com/328-hexbin-map-of-the-usa.html 

# Download the Hexagones boundaries at geojson format here:
#     https://team.carto.com/u/andrew/tables/andrew.us_states_hexgrid/public/map.

# Load downloaded file 
spdf <- geojsonio::geojson_read("data/us_states_hexgrid.geojson",  what = "sp")

spdf@data <-  spdf@data %>% 
  mutate(
    google_name = gsub(" \\(United States\\)", "", google_name)
    , state_pc = iso3166_2
  )
spdf_fortified <- broom::tidy(spdf, region = "state_pc")


current_date <- max(covid19$date)

quant_state <- covid19 %>% 
  filter(geo %in% c(state.abb, "DC", "USA")) %>%
  filter(date == current_date) %>%
  pull(case_total_PC) %>%
  quantile(prob = quant_perc)

df <- covid19 %>% 
  filter(geo %in% c(state.abb, "DC", "USA")) %>%
  filter(date == current_date) %>%
  mutate(
      quantile = cut(
        case_total_PC
        , breaks = c(-Inf, quant_state, Inf)
        , labels = quant_labels
        , right = FALSE
        )
    , font_color = SET_FONT_COLOR_quant(quantile)
  ) 

max_date <- max(covid19$date)

hex_data<- spdf_fortified %>%
  left_join(. , df, by=c("id" = "geo") ) 



#HEX MAP STATE LABELS 
# Calculate the centers of each hexagon to add the labels:
#requires rgeos package 
centers <- cbind.data.frame(data.frame(rgeos::gCentroid(spdf, byid=TRUE), id=spdf@data$iso3166_2))


labels <- centers %>%
  left_join(., hex_data, by = c("id" = "id")) 


USA_data <- df %>% filter(geo == "USA") %>% filter(date == max_date)
title <- paste("Total Cases as Percent of Population as of ", max_date)
USA_val_text <- paste0("National US value: ", percent(USA_data$case_total_PC, accuracy = 0.1))

USA_bg_color <- quant_colors[names(quant_colors) == USA_data$quantile]
USA_ft_color <- SET_FONT_COLOR_quant(USA_data$quantile)

hex_data$USA_val <- USA_val_text

ggplot(data = hex_data, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill = quantile)) +
  geom_polygon(color = "white", fill = NA, size = 1, show.legend = FALSE) +
  geom_polygon(data = subset(hex_data, font_color == "black"), color = "grey80", fill = NA, size = 0.25 ) +  
  facet_grid( . ~ USA_val) + 
  scale_fill_manual(
      name = NULL
    , values = quant_colors
    , drop = FALSE #show all categories
  ) + 
  guides(fill=guide_legend(title.position="top")) + 
  geom_text(
    data = labels
    , aes(x=x, y=y+0.5, label=id)
    , color = labels$font_color 
    , fontface = "bold"
  ) +
  geom_text(
    data = labels
    , aes(x=x, y=y-0.8, label=scales::percent(case_total_PC, accuracy = 0.1))
    , color = labels$font_color
    , size = 2.5
  ) +
  theme_void() +
  coord_map() +
  labs(title = title) +
  theme(
      plot.title = element_text(face = "bold", hjust = 0.5, margin = margin(0, 0, 10, 0))
    , plot.subtitle = element_text(hjust = 0.5, size = subtitle_size)
    , strip.text.x  = element_text(size = 12, color = USA_ft_color, face = "bold", margin = margin(3, 0, 3, 0))
    , strip.background.x = element_rect(fill = USA_bg_color, color = USA_bg_color,)
    , legend.spacing.x = unit(0, 'cm')
    , legend.margin=margin(t = .5, unit='cm')
    , legend.position = "bottom"
    , legend.text = element_text(margin = margin(0,12,0,3)) # t r b l
  )
```

<br> 

```{r county-total-MA7-PC, fig.height=5, fig.width = 8}
state_sf  <- get_urbn_map("states", sf = TRUE)
counties_sf <- get_urbn_map("counties", sf = TRUE) %>% 
  #data import fips doesn't have 0's at begining of certain FIPS; so convert to numeric and then back to charcter to remove leading zeros 
  mutate(
      county_fips = as.numeric(county_fips)
    , county_fips = as.character(county_fips)
  )

quant_cnty <- covid19_county %>% 
  pull(case_total_PC) %>%
  quantile(prob = quant_perc, na.rm = TRUE)

county_map_data <- covid19_county  %>% 
 filter(date == current_date) %>%
  mutate(
      quantile = cut(
        case_total_PC
        , breaks = c(-Inf, quant_cnty, Inf)
        , labels = quant_labels
        , right = FALSE
        )
  ) %>% 
  select(date, county_fips, case_total_PC, quantile) %>%
  left_join(., counties_sf, by = "county_fips")

lower48_sf  <- get_urbn_map("states", sf = TRUE) %>% subset(!state_abbv %in% c("AK", "HI"))
lower48_border <- st_union(lower48_sf)

ggplot() +
  geom_sf(data = county_map_data, aes(geometry = geometry, fill = quantile), color = NA) + 
  geom_sf(data = state_sf,        aes(geometry = geometry), color = "white", fill = NA) + 
  geom_sf(data = lower48_border, aes(geometry = geometry), fill = NA, color = "grey50") + 
  geom_sf(data = subset(state_sf, state_abbv %in% c("AK", "HI")), aes(geometry = geometry), color = "grey50", fill = NA) + 
  #facet_grid( . ~ USA_val) + 
  scale_fill_manual(
      name = NULL
    , values = quant_colors
    , drop = FALSE #show all categories
    , na.value = "grey70"
  ) +
  theme_void() +
  coord_sf() +
  #labs(title = title ) +
  theme(
      plot.title = element_text(face = "bold", hjust = 0.5, margin = margin(0, 0, 10, 0))
    , plot.subtitle = element_text(hjust = 0.5, size = 12)
    , strip.text.x  = element_text(size = 12, color = "white", face = "bold", margin = margin(3, 0, 3, 0))
    , strip.background.x = element_rect(fill = USA_bg_color, color = USA_bg_color,)
    , legend.spacing.x = unit(0, 'cm')
    , legend.margin=margin(t = .5, unit='cm')
    , legend.position = "none"
    , legend.text = element_text(margin = margin(0,12,0,3)) # t r b l
  )

```








