---
title: "double axis chart"
output: html_document
---

```{r}
#start by defining two fucntion

#round number to specific base  
func_mround <- function(x, base){
  base*round(x/base)
}

#round up to a certain base; this will be used for upper bound for primary axis 
Ylim <- function(curr_val, base){
round_curr_val <- func_mround(curr_val, base)
if( round_curr_val - curr_val < 0 ){
  lim <- round_curr_val + base
} else {
  lim <- round_curr_val
}
return(lim)
}
```

```{r}
#td = total deaths 
#set base for primary axis 
dd_base <- 1000

#primary/main y-axis limit 
dd_y1lim  <- Ylim(max(covid19_US_adj$new_deaths), dd_base)
  #add an extra base to add more room 


#TRANSFORM PRIMARY AXIS TO SECONDARY AXIS 
#in order to have a secondary axis have to have a multiplier to transform primary axis to sec axis
#find the Ylim of primary axis
# next want to find an upper bound for seconday axis
#     want both upper bounds to be divisible by the same number 
#     i.e. if the primary axis is from 0 to 20 and it has 4 breaks (5, 10, 15, 20)
#     I want to set the upper bound of the secondary axis to a value divisible by 4
#     want teh break lines of the primary axis to match up with the breaks of the secondary axis 
#what if I don't do this?
#     the text breaks of the seconday axis will not line up with the line breaks of the primary axis 

#find what the divisor is 
divisor <- dd_y1lim/dd_base

#max value for the secondary axis 
maxdeathperc <- max(covid19_US_adj$death_percentage, na.rm=TRUE)


dp_y2lim  <- Ylim(maxdeathperc, .01)+.01

dp_base <- dp_y2lim/divisor

#calculate the breaks 
dd_y1breaks <- c(1:divisor)*dd_base
dp_y2breaks <- c(1:divisor)*dp_base

#calculate the transform multiplier 
dd_transform <- dd_y1lim*(1/dp_y2lim)
```


```{r}
#plot the primary data: new deaths by day bar chart    

plot_dd <- ggplot(covid19_US_adj, aes(x=date))+
  #use geom_col because counts per day have alread been counted 
  geom_col(aes(y=new_deaths), alpha=0.6)+
  #add total dealths label 
  geom_label(
      data = current_values
    #format label so there is a comma after three places 
    , aes(
        label = formatC(new_deaths, big.mark=",", format="d")
      , y     = new_deaths
      )
    , hjust = 0.75
    , nudge_y = 250
    )
```

```{r}
#Then, plot the secondary data: death percentage.  

plot_dd <- plot_dd + 
  geom_line(
    data = covid19_US_adj, 
    #transformatio to match secondary axis below
      aes(y=death_percentage*dd_transform)
    , color=gf2plus
    , size= 1
    )+
  geom_point(
    data = covid19_US_adj, 
    #transformatio to match secondary axis below
      aes(y=death_percentage*dd_transform)
    #color 
    , color=gf2plus
    , size= 2
    )+
  #add label to most recent value 
  geom_label(
      data = current_values
    , aes(
        label = percent(death_percentage, accuracy=0.001)
      # remember to add the transform! 
      , y     = death_percentage*dd_transform 
      )
    , hjust = 0.75
    , vjust = 0
    , nudge_y = .0020 * dd_transform 
    , color = gf2plus
    )
```

```{r }
#It is imparative to add the scales.  

plot_dd <- plot_dd + 
  #scale the date to be onece a week 
  #add specific limits so it will line up with geom_line 
  date_scaling +
  #add commas to numbers in y axis; requires scales package
  scale_y_continuous(
      limits = c(0, dd_y1lim)
    , breaks = dd_y1breaks
    #add commas to numbers in y axis; requires scales package
    , labels = scales::unit_format(unit = "k", scale = 1e-3, accuracy = 1, big.mark = ",")
    #this transformation MUST match the transformation above
    #divide by current_US_deaths leads to an axis of 0 to 1
    #divide by current_US_deaths*10 leads to an axis of 0 to 0.1
    , sec.axis = sec_axis(
        ~./dd_transform
      ,  breaks = dp_y2breaks
      )
    )
```

```{r }
#Finally, a title and other themes are specified.    

plot_dd <- plot_dd + 
  #add title 
  ggtitle("New Deaths and Dealth Percentage of COVID-19 in the United States by Day")+
  #minimal theme
  theme_minimal()+
  theme(
    #remove all legents 
     legend.position = "none"
     # remove x and y axes 
    , axis.title.x = element_blank()
    , axis.title.y = element_blank()
    #adjust plot title 
    , plot.title = element_text(hjust = 0.5, size = title_size)
  )

plot_dd
```
